export const currentData = [
  {
    id: 1,
    company: "MARK GLAZE TILES PVT LTD",
    contact: "Gopal Lakhmanbhai Moradiya",
    address: "Survey No: 565 & 566 Old Ghuntu Road Morbi - 363642",
    product: "Ceramic Tiles",
    area: "Bhopal",
    imageLogo: "/companyLogo/logo1.png",
  },
  {
    id: 2,
    company: "PLATINUM CERAMIC PVT LTD",
    contact: "Hiteshbhai Godhaviya",
    address: "Morbi Jetpar road, Opp. Art tile, At jasmatgadh, Morbi",
    product: "Floor Tiles",
    area: "Betul",
    imageLogo: "/companyLogo/logo1.png",
  },
  {
    id: 3,
    company: "Example Company 1",
    contact: "Person 1",
    address: "Industrial Area 1, Bhopal",
    product: "Product A",
    area: "Bhopal",
    imageLogo: "/companyLogo/logo1.png",
  },
  {
    id: 4,
    company: "Example Company 2",
    contact: "Person 2",
    address: "Industrial Area 2, Bhopal",
    product: "Product B",
    area: "Bhopal",
    imageLogo: "/companyLogo/logo1.png",
  },
  {
    id: 5,
    company: "Example Company 3",
    contact: "Person 3",
    address: "Industrial Area 3, Bhopal",
    product: "Product C",
    area: "mp",
    imageLogo: "/companyLogo/logo1.png",
  },
  {
    id: 6,
    company: "Example Company 4",
    contact: "Person 4",
    address: "Govindpura Industrial Area, Bhopal",
    product: "Product D",
    area: "Indore",
    imageLogo: "/companyLogo/logo1.png",
  },
  {
    id: 7,
    company: "Example Company 5",
    contact: "Person 5",
    address: "BHEL Industrial Area, Bhopal",
    product: "Product E",
    area: "Betul",
    imageLogo: "/companyLogo/logo1.png",
  },
  {
    id: 8,
    company: "Example Company 6",
    contact: "Person 6",
    address: "Mandideep Industrial Area, Bhopal",
    product: "Product F",
    area: "Bhopal",
    imageLogo: "/companyLogo/logo1.png",
  },
  {
    id: 9,
    company: "Example Company 7",
    contact: "Person 7",
    address: "Industrial Area 7, Bhopal",
    product: "Product G",
    area: "Indore",
    imageLogo: "/companyLogo/logo1.png",
  },
  {
    id: 10,
    company: "Example Company 8",
    contact: "Person 8",
    address: "Industrial Area 8, Bhopal",
    product: "Product H",
    area: "Betul",
    imageLogo: "/companyLogo/logo1.png",
  },
  {
    id: 11,
    company: "Example Company 9",
    contact: "Person 9",
    address: "Industrial Area 9, Bhopal",
    product: "Product I",
    area: "Indore",
    imageLogo: "/companyLogo/logo1.png",
  },
  {
    id: 12,
    company: "Example Company 10",
    contact: "Person 10",
    address: "Industrial Area 10, Bhopal",
    product: "Product J",
    area: "Betul",
    imageLogo: "/companyLogo/logo1.png",
  },
  {
    id: 13,
    company: "Bhopal Engineering Works",
    contact: "Suresh Kumar",
    address: "Industrial Area 11, Bhopal",
    product: "Heavy Machinery",
    area: "Indore",
    imageLogo: "/companyLogo/logo1.png",
  },
  {
    id: 14,
    company: "Central India Fabrics",
    contact: "Rajesh Mehta",
    address: "Industrial Area 12, Bhopal",
    product: "Textiles",
    area: "Betul",
    imageLogo: "/companyLogo/logo1.png",
  },
  {
    id: 15,
    company: "Zenith Metals Pvt Ltd",
    contact: "Amit Rathore",
    address: "Industrial Area 13, Bhopal",
    product: "Metal Sheets",
    area: "Indore",
    imageLogo: "/companyLogo/logo1.png",
  },
  {
    id: 16,
    company: "GreenTech Solutions",
    contact: "Alok Verma",
    address: "Industrial Area 14, Bhopal",
    product: "Solar Panels",
    area: "Betul",
    imageLogo: "/companyLogo/logo1.png",
  },
  {
    id: 17,
    company: "EcoTiles Pvt Ltd",
    contact: "Sandeep Sharma",
    address: "Industrial Area 15, Bhopal",
    product: "Ceramic Tiles",
    area: "Indore",
    imageLogo: "/companyLogo/logo1.png",
  },
  {
    id: 18,
    company: "Precision Tools Corp",
    contact: "Manish Jain",
    address: "Industrial Area 16, Bhopal",
    product: "Precision Tools",
    area: "Betul",
    imageLogo: "/companyLogo/logo1.png",
  },
  {
    id: 19,
    company: "Future Plastics",
    contact: "Deepak Singh",
    address: "Industrial Area 17, Bhopal",
    product: "Plastic Products",
    area: "Indore",
    imageLogo: "/companyLogo/logo1.png",
  },
  {
    id: 20,
    company: "TechnoSteel Ltd",
    contact: "Pawan Patel",
    address: "Industrial Area 18, Bhopal",
    product: "Steel Products",
    area: "Betul",
    imageLogo: "/companyLogo/logo1.png",
  },
  {
    id: 21,
    company: "Hydro Pumps & Systems",
    contact: "Nilesh Gupta",
    address: "Industrial Area 19, Bhopal",
    product: "Water Pumps",
    area: "Indore",
    imageLogo: "/companyLogo/logo1.png",
  },
  {
    id: 22,
    company: "Global Gears Ltd",
    contact: "Arvind Mishra",
    address: "Industrial Area 20, Bhopal",
    product: "Automotive Gears",
    area: "Betul",
    imageLogo: "/companyLogo/logo1.png",
  },
  {
    id: 23,
    company: "Ace Textiles Pvt Ltd",
    contact: "Vikram Chauhan",
    address: "Industrial Area 21, Bhopal",
    product: "Fabrics",
    area: "Indore",
    imageLogo: "/companyLogo/logo1.png",
  },
  {
    id: 24,
    company: "Energy Savers Ltd",
    contact: "Ravi Kapoor",
    address: "Industrial Area 22, Bhopal",
    product: "Energy Solutions",
    area: "Betul",
    imageLogo: "/companyLogo/logo1.png",
  },
  {
    id: 25,
    company: "NovaChem Pvt Ltd",
    contact: "Siddharth Sen",
    address: "Industrial Area 23, Bhopal",
    product: "Chemicals",
    area: "Indore",
    imageLogo: "/companyLogo/logo1.png",
  },
  {
    id: 26,
    company: "InnoTech Industries",
    contact: "Vivek Gupta",
    address: "Industrial Area 24, Bhopal",
    product: "Innovative Solutions",
    area: "Betul",
    imageLogo: "/companyLogo/logo1.png",
  },
  {
    id: 27,
    company: "FusionWorks",
    contact: "Harish Chawla",
    address: "Industrial Area 25, Bhopal",
    product: "Industrial Automation",
    area: "Indore",
    imageLogo: "/companyLogo/logo1.png",
  },
  {
    id: 28,
    company: "Prime Woodcrafts Ltd",
    contact: "Rajiv Saxena",
    address: "Industrial Area 26, Bhopal",
    product: "Wooden Furniture",
    area: "Betul",
    imageLogo: "/companyLogo/logo1.png",
  },
  {
    id: 29,
    company: "AutoSpare Ltd",
    contact: "Akash Singh",
    address: "Industrial Area 27, Bhopal",
    product: "Auto Spare Parts",
    area: "Indore",
    imageLogo: "/companyLogo/logo1.png",
  },
  {
    id: 30,
    company: "Pioneer Glass Ltd",
    contact: "Rohan Bhatt",
    address: "Industrial Area 28, Bhopal",
    product: "Glass Products",
    area: "Betul",
    imageLogo: "/companyLogo/logo1.png",
  },
];
