export const products = [
    // Herbal Products
    {
      name: "शुगर की फक्की",
      englishName: "Sugar Fakki",
      size: "200 gm",
      mrp: 180,
      offerPrice: 160,
      image: "/productsPage/product/herbal.png",
      category: "Herbal",
    },
    {
      name: "अमेरिकन मशरूम",
      englishName: "American Mushroom",
      size: "100 gm",
      mrp: 400,
      offerPrice: 350,
      image: "/productsPage/product/herbal.png",
      category: "Herbal",
    },
    {
      name: "अश्वगंधा चूर्ण",
      englishName: "Ashwagandha Powder",
      size: "150 gm",
      mrp: 220,
      offerPrice: 199,
      image: "/productsPage/product/herbal.png",
      category: "Herbal",
    },
    {
      name: "शतावरी चूर्ण",
      englishName: "Shatavari Powder",
      size: "100 gm",
      mrp: 190,
      offerPrice: 165,
      image: "/productsPage/product/herbal.png",
      category: "Herbal",
    },
    
    // Capsule Products
    {
      name: "प्रोटी प्लस",
      englishName: "Proti Plus",
      size: "400 gm",
      mrp: 600,
      offerPrice: 505,
      image: "/productsPage/product/capsule.png",
      category: "Capsule",
    },
    {
      name: "अश्वगंधा कैप्सूल",
      englishName: "Ashwagandha Capsules",
      size: "60 capsules",
      mrp: 450,
      offerPrice: 399,
      image: "/productsPage/product/capsule.png",
      category: "Capsule",
    },
    {
      name: "त्रिफला कैप्सूल",
      englishName: "Triphala Capsules",
      size: "60 capsules",
      mrp: 350,
      offerPrice: 299,
      image: "/productsPage/product/capsule.png",
      category: "Capsule",
    },
    {
      name: "तुलसी कैप्सूल",
      englishName: "Tulsi Capsules",
      size: "90 capsules",
      mrp: 375,
      offerPrice: 325,
      image: "/productsPage/product/capsule.png",
      category: "Capsule",
    },
    
    // Ayurvedic Oils
    {
      name: "नारायण तेल",
      englishName: "Narayan Oil",
      size: "100 ml",
      mrp: 290,
      offerPrice: 245,
      image: "/productsPage/product/ayurvedicoils.png",
      category: "Ayurvedic Oils",
    },
    {
      name: "महानारायण तेल",
      englishName: "Mahanarayana Oil",
      size: "200 ml",
      mrp: 410,
      offerPrice: 359,
      image: "/productsPage/product/ayurvedicoils.png",
      category: "Ayurvedic Oils",
    },
    {
      name: "पंचगुण तेल",
      englishName: "Panchagun Oil",
      size: "100 ml",
      mrp: 275,
      offerPrice: 235,
      image: "/productsPage/product/ayurvedicoils.png",
      category: "Ayurvedic Oils",
    },
    {
      name: "अनु तेल",
      englishName: "Anu Oil",
      size: "50 ml",
      mrp: 195,
      offerPrice: 175,
      image: "/productsPage/product/ayurvedicoils.png",
      category: "Ayurvedic Oils",
    },
    
    // Hair Oil
    {
      name: "भृंगराज तेल",
      englishName: "Bhringraj Hair Oil",
      size: "200 ml",
      mrp: 320,
      offerPrice: 275,
      image: "/productsPage/product/hairoil.png",
      category: "Hair Oil",
    },
    {
      name: "अमला हेयर ऑयल",
      englishName: "Amla Hair Oil",
      size: "100 ml",
      mrp: 150,
      offerPrice: 125,
      image: "/productsPage/product/hairoil.png",
      category: "Hair Oil",
    },
    {
      name: "नीम हेयर ऑयल",
      englishName: "Neem Hair Oil",
      size: "100 ml",
      mrp: 180,
      offerPrice: 150,
      image: "/productsPage/product/hairoil.png",
      category: "Hair Oil",
    },
    {
      name: "जटामांसी हेयर ऑयल",
      englishName: "Jatamansi Hair Oil",
      size: "150 ml",
      mrp: 260,
      offerPrice: 230,
      image: "/productsPage/product/hairoil.png",
      category: "Hair Oil",
    },
    
    // Gel Balm
    {
      name: "अर्निका जेल",
      englishName: "Arnica Gel",
      size: "50 g",
      mrp: 175,
      offerPrice: 145,
      image: "/productsPage/product/gelbalm.png",
      category: "Gel Balm",
    },
    {
      name: "पेन रिलीफ बाम",
      englishName: "Pain Relief Balm",
      size: "30 g",
      mrp: 120,
      offerPrice: 99,
      image: "/productsPage/product/gelbalm.png",
      category: "Gel Balm",
    },
    {
      name: "संधिवात जेल",
      englishName: "Arthritis Relief Gel",
      size: "75 g",
      mrp: 220,
      offerPrice: 199,
      image: "/productsPage/product/gelbalm.png",
      category: "Gel Balm",
    },
    {
      name: "कूलिंग मेंथॉल जेल",
      englishName: "Cooling Menthol Gel",
      size: "100 g",
      mrp: 190,
      offerPrice: 170,
      image: "/productsPage/product/gelbalm.png",
      category: "Gel Balm",
    },
    
    // Syrup
    {
      name: "चयवनप्राश",
      englishName: "Chyawanprash",
      size: "500 g",
      mrp: 340,
      offerPrice: 299,
      image: "/productsPage/product/syrup.png",
      category: "Syrup",
    },
    {
      name: "कफ सिरप",
      englishName: "Cough Syrup",
      size: "200 ml",
      mrp: 150,
      offerPrice: 129,
      image: "/productsPage/product/syrup.png",
      category: "Syrup",
    },
    {
      name: "अश्वगंधारिष्ट",
      englishName: "Ashwagandharishta",
      size: "450 ml",
      mrp: 280,
      offerPrice: 245,
      image: "/productsPage/product/syrup.png",
      category: "Syrup",
    },
    {
      name: "गिलोय सत्व सिरप",
      englishName: "Giloy Satva Syrup",
      size: "300 ml",
      mrp: 230,
      offerPrice: 199,
      image: "/productsPage/product/syrup.png",
      category: "Syrup",
    }
  ];